url: https://kontingenz.github.io
baseurl: ""

# Site settings
title: Kontingenz
email: data@kontingenz.com
description: "Data science."


# Team names, titles and social links
people:

- name: Luke Miller
  pic: 4
  position: Physicist 
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Felix Müller
  pic: 3
  position: Software developer
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: google-plus
    #   url: #
- name: Philipp Müller
  pic: 2
  position: Economist
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: linkedin
    #   url: #


- name: Christoph Schwerdtfeger
  pic: 1
  position: Mathematician
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Combahnstrasse 18
  - line: 53225 Bonn
  - line: Germany

# Build settings
markdown: kramdown
permalink: pretty
